apiVersion: v1
kind: ReplicationController
metadata:
  name: poi
spec:
  replicas: 3
  selector:
    app: poi
  template:
    metadata:
      labels: 
        app: poi
    spec:
      containers:
      - name: poi
        image: poistargram/poi
        ports:
        - containerPort: 8080
