apiVersion: v1
kind: Pod
metadata:
  name: poi-liveness
spec:
  containers:
  - image: poistargram/poi-error
    name: poi
    livenessProbe:
      httpGet:
        path: /error
        port: 8080
  
