apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: poi-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: poistargram/poi-error
